### PR TITLE
cuckoo sandbox templates

### PR DESCRIPTION
**Pull request by juju4**
Hello,

I forked win7 and win10 with cuckoo variant
cuckoo is a malware analysis system, see http://cuckoosandbox.org/

These templates and scripts allow fast creation of the box with system and apps pre-installed.
I tested scripts independently.
I did not manage to add valid entries to Makefile for now. it's variant like ssh or cygwin as far as I'm concerned.

Thanks

### CODE REVIEW

**Comment by annawake** [comment]
This appears to be a kind of contribution that is out of scope for the kind of templates boxcutter intends to be - "Just Enough OS" (JEOS) for a configuration management system to install.

This is basically installing a malware scanning app, no? And this is something that could be done after the OS is configured, yes?

Why ssh or cygwin? Well at one point they were required to work with packer only supported the ssh transport when it did not support winrm. They are now regarded as vestigial and we will likely retire these at some point as well.

It is more appropriate to be using some configuration management system to do this on top of these templates, to make it easy to reconfigure. Not to mention that there are so many apps we could choose to have installed by default, that instead we just want to provide as bare-bones of an image that might have the broadest appeal/use.

The only extra functionality we may add to these boxes is a way to capture the result of a configuration management run to a box - for most CM tools this is non-trivial with packer, unfortunately. We only really want to focus on automating the core OS install itself in these templates.

**Comment by juju4** [comment]
No, it's not installing malware scanning app. It is just a windows box template than can be used by the tool as a starting point to run/analyze a piece of software or url. Solution is using a box template as input so at some point, it needs to be packed.
I quote ssh and cygwin just as a variant model.

I agree that maybe to specific need for general usage but for IT/security person, that simplify/accelerate installation and usage.
Else, can you just hint me on how to customize Makefile to support those json?

Thanks

**Comment by annawake** [comment]
I'm confused - how are you enhancing the core Windows install for anyone trying to install Windows? This looks like it should be its own repo if you're just trying to capture the result of some application installs for a Windows malware analysis distribution. This is more in the realm of configuration management.

**Comment by juju4** [comment]
It's definitely not for anyone, mostly sysadmin/security people. I will cancel the pull request.
I managed to get Makefile working by switching s/-cygwin/-cuckoo/g

**Pull request closed without merging**
