### PR TITLE
fixed cmtool assumption x64 chef-client exists

### PR DESCRIPTION
**Pull request by daxgames**

### CODE REVIEW

**Comment by daxgames** [comment]
bump - Who can merge this, it fixes a bug

**Comment by emachnic** [comment]
Is this working for you? It looks like Chef may have changed the URL to be like the following:

https://packages.chef.io/files/stable/chef/12.12.15/windows/2008r2/chef-client-12.12.15-1.x64.msi

Note the extra "files", version, and the extra "1" right before the architecture. I think @annawake's suggestion in issue #32 may be the most robust option. Thoughts?

**Comment by emachnic** [comment]
```
⋊> curl 'https://omnitruck.chef.io/stable/chef/metadata?p=windows&pv=2008r2&m=x86_64&v=12.12.15'
sha1    9da3b90ff22d7985a0a5c301a71d1f91ce272fbb
sha256  1566ceb106ccb4c5e7bd7135cdc289838fb36219cf6a343652f0118c29aab6df
url     https://packages.chef.io/files/stable/chef/12.12.15/windows/2012r2/chef-client-12.12.15-1-x64.msi
version 12.12.15
⋊> 
```

**Comment by daxgames** [comment]
The issue is not a change in url.  The issue is x64 clients are only available after 12.7. Released.  This fixes that.

**Comment by daxgames** [comment]
And yes it does work.

**Comment by daxgames** [comment]
Ok so its a moving target.  I looked again and when I wrote this it worked and the x64 versions were only available for 12.7.x and newer and the URL has changed.

Now it looks like the x64 versions are available as old as 12.4.2.

https://packages.chef.io/files/stable/chef/12.7.2/windows/2012r2/chef-client-12.7.2-1-x64.msi
https://packages.chef.io/files/stable/chef/12.7.2/windows/2012r2/chef-client-12.7.2-1-x86.msi
https://packages.chef.io/files/stable/chef/12.6.0/windows/2012r2/chef-client-12.6.0-1-x64.msi
https://packages.chef.io/files/stable/chef/12.6.0/windows/2012r2/chef-client-12.6.0-1-x86.msi
https://packages.chef.io/files/stable/chef/12.5.1/windows/2012r2/chef-client-12.5.1-1-x64.msi
https://packages.chef.io/files/stable/chef/12.5.1/windows/2012r2/chef-client-12.5.1-1-x86.msi
https://packages.chef.io/files/stable/chef/12.4.3/windows/2008r2/chef-client-12.4.3-1-x64.msi
https://packages.chef.io/files/stable/chef/12.4.3/windows/2008r2/chef-client-12.4.3-1-x86.msi
https://packages.chef.io/files/stable/chef/12.4.2/windows/2008r2/chef-client-12.4.2-1-x64.msi
https://packages.chef.io/files/stable/chef/12.4.2/windows/2008r2/chef-client-12.4.2-1-x86.msi
https://packages.chef.io/files/stable/chef/12.4.1/windows/2008r2/chef-client-12.4.1-1.msi

I will update the PR.

**Comment by daxgames** [comment]
I have the omnitruck api mentioned in #32 working in the cmtool script.  just testing it now, will update the pr soon.

**Comment by daxgames** [comment]
closed to open a new pr since current code is COMPLETELY different from the original pr

**Pull request closed without merging**
