### PR TITLE
Updated win2012r2 to use Nov2014 update rollup iso

### PR DESCRIPTION
**Pull request by echohack**
Updated win2012r2 to use Nov2014 update rollup iso -- Downloadable via
an MSDN subscription.

Tested out builds using packer and the machines built just fine. Using these internally for Chef Windows needs.

Let me know if you need additional validation or tests!

### CODE REVIEW

**Comment by rasa** [comment]
These get overwritten by the values in [Makefile](../blob/master/Makefile#L35)

**Comment by echohack** [comment]
Shouldn't we provide good defaults for consumers of boxcutter?
If you're using winr2012r2 standard this is the current modern release of the platform.

**Comment by rasa** [comment]
Agreed. My comment was to alert us that we'll need to update the Makefile as well with these new values. Sorry if that wasn't clear.

**Comment by rasa** [comment]
Thanks for your contribution. Much appreciated!

**Comment by echohack** [comment]
@rasa Makefile update is included in the PR. Thanks!

**Pull request merged**
