### PR TITLE
Fix shutdown command

### LINKED ISSUE #255: Not using Makefile causes errors due to incorrectly formatted `shutdown` comment string and other things
It appears that the iso_url, iso_checksum, and shutdown_command and several other things (CM variable) are overridden from the templates defaults by the Makefile, meaning there are possibly a lot of partially invalid templates that can't actually be built directly with `packer build --only virtualbox-iso eval-win10x64-enterprise.json`.

It is non-intuitive that a user can't just look at the json template, they also have to dive into the Makefile and figure out which environment variables correspond to options, *if* they even realize that they can do overrides with environment variables. The use of environment variables makes sense if you are always running in a CI pipeline where they can persist between runs and be logged as part of the build, but if you only build a box occasionally or are building something locally it is time lost looking up the differences from the actual json pretty much every time.

The json templates contains the iso_url and iso_checksum and some sane defaults for `headless` and `update` (but sadly not `cm` which is set to `chef` which is a great tool but fails to install sometimes) but the fact that the `Makefile` overrides any changes a user might make to these core settings in the template json seems bad and has caught me out several times when trying to make changes.

It appears the root of issue described in the subject here is that the version of the `shutdown_command` in the templates has a space in the `/c` shutdown comment, where as you can see below the `make` executed version uses an override to swaps in an underscore to eliminate the space and removes the need for the quotes.

While debugging this I also discovered much to my dismay that if not using `make` the default CM option coming from the template files is `chef` and due to some infrastructure quirks the omnitruck site throws a 500 error causing builds to fail hard unless explicitly setting `-var 'cm=nocm'` when calling `packer build`.

Assembled command from `make virtualbox/eval-win10x64-enterprise`

```
packer build -on-error=cleanup -only=virtualbox-iso -var 'cm=nocm' -var 'version=1.0.4' -var 'update=false' -var 'headless=false' -var "shutdown_command=shutdown /s /t 10 /f /d p:4:1 /c Packer_Shutdown" -var "iso_url=https://long.url.string/file.iso" -var "iso_checksum=aCheckSum" eval-win10x64-enterprise.json
```

Many templates have it using single quotes
```
shutdown /s /t 10 /f /d p:4:1 /c 'Packer Shutdown'
```

A couple have escaped double quotes
```
shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"
```

Example of error I was getting
```
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Usage: shutdown [/i | /l | /s | /sg | /r | /g | /a | /p | /h | /e | /o] [/hybrid] [/soft] [/fw] [/f]
    virtualbox-iso:     [/m \\computer][/t xxx][/d [p|u:]xx:yy [/c "comment"]]
    virtualbox-iso:
    virtualbox-iso:     No args    Display help. This is the same as typing /?.
    virtualbox-iso:     /?         Display help. This is the same as not typing any options.
    virtualbox-iso:     /i         Display the graphical user interface (GUI).
    virtualbox-iso:                This must be the first option.
    virtualbox-iso:     /l         Log off. This cannot be used with /m or /d options.
    virtualbox-iso:     /s         Shutdown the computer.
    virtualbox-iso:     /sg        Shutdown the computer. On the next boot, if Automatic Restart Sign-On
    virtualbox-iso:                is enabled, automatically sign in and lock last interactive user.
    virtualbox-iso:                After sign in, restart any registered applications.
    virtualbox-iso:     /r         Full shutdown and restart the computer.
    virtualbox-iso:     /g         Full shutdown and restart the computer. After the system is rebooted,
    virtualbox-iso:                if Automatic Restart Sign-On is enabled, automatically sign in and
    virtualbox-iso:                lock last interactive user.
    virtualbox-iso:                After sign in, restart any registered applications.
    virtualbox-iso:     /a         Abort a system shutdown.
    virtualbox-iso:                This can only be used during the time-out period.
    virtualbox-iso:                Combine with /fw to clear any pending boots to firmware.
    virtualbox-iso:     /p         Turn off the local computer with no time-out or warning.
    virtualbox-iso:                Can be used with /d and /f options.
    virtualbox-iso:     /h         Hibernate the local computer.
    virtualbox-iso:                Can be used with the /f option.
    virtualbox-iso:     /hybrid    Performs a shutdown of the computer and prepares it for fast startup.
    virtualbox-iso:                Must be used with /s option.
    virtualbox-iso:     /fw        Combine with a shutdown option to cause the next boot to go to the
    virtualbox-iso:                firmware user interface.
    virtualbox-iso:     /e         Document the reason for an unexpected shutdown of a computer.
    virtualbox-iso:     /o         Go to the advanced boot options menu and restart the computer.
    virtualbox-iso:                Must be used with /r option.
    virtualbox-iso:     /m \\computer Specify the target computer.
    virtualbox-iso:     /t xxx     Set the time-out period before shutdown to xxx seconds.
    virtualbox-iso:                The valid range is 0-315360000 (10 years), with a default of 30.
    virtualbox-iso:                If the timeout period is greater than 0, the /f parameter is
    virtualbox-iso:                implied.
    virtualbox-iso:     /c "comment" Comment on the reason for the restart or shutdown.
    virtualbox-iso:                Maximum of 512 characters allowed.
    virtualbox-iso:     /f         Force running applications to close without forewarning users.
    virtualbox-iso:                The /f parameter is implied when a value greater than 0 is
    virtualbox-iso:                specified for the /t parameter.
    virtualbox-iso:     /d [p|u:]xx:yy  Provide the reason for the restart or shutdown.
    virtualbox-iso:                p indicates that the restart or shutdown is planned.
    virtualbox-iso:                u indicates that the reason is user defined.
    virtualbox-iso:                If neither p nor u is specified the restart or shutdown is
    virtualbox-iso:                unplanned.
    virtualbox-iso:                xx is the major reason number (positive integer less than 256).
    virtualbox-iso:                yy is the minor reason number (positive integer less than 65536).
    virtualbox-iso:
    virtualbox-iso: Reasons on this computer:
    virtualbox-iso: (E = Expected U = Unexpected P = planned, C = customer defined)
    virtualbox-iso: Type        Major   Minor   Title
    virtualbox-iso:
    virtualbox-iso:  U          0       0       Other (Unplanned)
    virtualbox-iso: E           0       0       Other (Unplanned)
    virtualbox-iso: E P         0       0       Other (Planned)
    virtualbox-iso:  U          0       5       Other Failure: System Unresponsive
    virtualbox-iso: E           1       1       Hardware: Maintenance (Unplanned)
    virtualbox-iso: E P         1       1       Hardware: Maintenance (Planned)
    virtualbox-iso: E           1       2       Hardware: Installation (Unplanned)
    virtualbox-iso: E P         1       2       Hardware: Installation (Planned)
    virtualbox-iso: E           2       2       Operating System: Recovery (Unplanned)
    virtualbox-iso: E P         2       2       Operating System: Recovery (Planned)
    virtualbox-iso:   P         2       3       Operating System: Upgrade (Planned)
    virtualbox-iso: E           2       4       Operating System: Reconfiguration (Unplanned)
    virtualbox-iso: E P         2       4       Operating System: Reconfiguration (Planned)
    virtualbox-iso:   P         2       16      Operating System: Service pack (Planned)
    virtualbox-iso:             2       17      Operating System: Hot fix (Unplanned)
    virtualbox-iso:   P         2       17      Operating System: Hot fix (Planned)
    virtualbox-iso:             2       18      Operating System: Security fix (Unplanned)
    virtualbox-iso:   P         2       18      Operating System: Security fix (Planned)
    virtualbox-iso: E           4       1       Application: Maintenance (Unplanned)
    virtualbox-iso: E P         4       1       Application: Maintenance (Planned)
    virtualbox-iso: E P         4       2       Application: Installation (Planned)
    virtualbox-iso: E           4       5       Application: Unresponsive
    virtualbox-iso: E           4       6       Application: Unstable
    virtualbox-iso:  U          5       15      System Failure: Stop error
    virtualbox-iso:  U          5       19      Security issue (Unplanned)
    virtualbox-iso: E           5       19      Security issue (Unplanned)
    virtualbox-iso: E P         5       19      Security issue (Planned)
    virtualbox-iso: E           5       20      Loss of network connectivity (Unplanned)
    virtualbox-iso:  U          6       11      Power Failure: Cord Unplugged
    virtualbox-iso:  U          6       12      Power Failure: Environment
    virtualbox-iso:   P         7       0       Legacy API shutdown
==> virtualbox-iso: Timeout while waiting for machine to shutdown.
```

### PR DESCRIPTION
**Pull request by dragon788**
Fixes #255 

If you aren't using `make` to build templates you may have run into this issue.

### CODE REVIEW

**Comment by arizvisa** [comment]
Hm. Strange. I'm definitely not using make and haven't encountered this issue yet.

Just curious. What error does it emit in packer during the reboot?

**Comment by arizvisa** [comment]
Nvm. Saw it in the issue that you posted.

**Comment by dragon788** [comment]
Excluding the quotes is primarily to avoid issues with differences between how Windows versions or Packer versions treat them.

I hadn't noticed issues with it shutting down on older versions of Windows 10 when I bypassed `make`, but after upgrading to Packer 1.6.0 I've had to make a few tweaks due to very subtle behavior changes.

I was actually originally going to file this as an issue with the templates when overriding to a newer version of the Windows 10 ISO but in trying to narrow things down I rediscovered the Makefile overrides and found the quoting issues after using `make` still worked with the newer ISO.

**Comment by arizvisa** [comment]
Tested a couple of the eval builds, validated everything but the wip/*.json crap. It all works... Merging.

**Pull request merged**
