### PR TITLE
Use Chef Omnitruck API to get Chef/ChefDK URls

### PR DESCRIPTION
**Pull request by daxgames**
* Also updated Chef and ChefDK versions to latest stable

### CODE REVIEW

**Comment by daxgames** [comment]
Implemented Omnitruck API suggested in #32 

Also fixes assumption that x64 versions exist causing download failure older versions.

**Comment by daxgames** [comment]
Output from an older Chef 12.5.1 client run:

```
==> virtualbox-iso: Provisioning with shell script: script/cmtool.bat
    virtualbox-iso: ==> Setting HTTP Proxy....
    virtualbox-iso: ==> HTTP Proxy Set to 3.40.85.27:80
    virtualbox-iso: ==> Getting Chef 12.5.1 download URL
    virtualbox-iso: ==> Creating "C:\Users\vagrant\AppData\Local\Temp\chef"
    virtualbox-iso: ==> Downloading "https://packages.chef.io/files/stable/chef/12.5.1/windows/2012r2/chef-client-12.5.1-1-x86.msi" to "C:\Users\vagrant\AppData\Local\Temp\chef\chef-client-12.5.1-1-x86.ms
i"
    virtualbox-iso: ==> Installing Chef client 12.5.1
    virtualbox-iso: 2016-12-14 09:52:00 URL:https://packages.chef.io/files/stable/chef/12.5.1/windows/2012r2/chef-client-12.5.1-1-x86.msi [78307328/78307328] -> "C:/Users/vagrant/AppData/Local/Temp/chef/c
hef-client-12.5.1-1-x86.msi" [1]
    virtualbox-iso:
    virtualbox-iso: Pinging 127.0.0.1 with 32 bytes of data:
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso:
    virtualbox-iso: Ping statistics for 127.0.0.1:
    virtualbox-iso: Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    virtualbox-iso: Approximate round trip times in milli-seconds:
    virtualbox-iso: Minimum = 0ms, Maximum = 0ms, Average = 0ms
    virtualbox-iso: ==> Script exiting with errorlevel 0
```

**Comment by daxgames** [comment]
Output from an newer Chef 12.16.42 client run omnitruck returns an Chef-Client x64 URL:

```
==> virtualbox-iso: Provisioning with shell script: script/cmtool.bat
    virtualbox-iso: ==> Getting Chef 12.16.42 download URL
    virtualbox-iso: ==> Creating "C:\Users\vagrant\AppData\Local\Temp\chef"
    virtualbox-iso: ==> Downloading "https://packages.chef.io/files/stable/chef/12.16.42/windows/2012r2/chef-client-12.16.42-1-x64.msi" to "C:\Users\vagrant\AppData\Local\Temp\chef\chef-client-12.16.42-1-x64.msi"
    virtualbox-iso: ==> Installing Chef client 12.16.42
    virtualbox-iso: 2016-12-14 10:09:30 URL:https://packages.chef.io/files/stable/chef/12.16.42/windows/2012r2/chef-client-12.16.42-1-x64.msi [177176576/177176576] -> "C:/Users/vagrant/AppData/Local/Temp/chef/chef-client-12.16.42-1-x64.msi" [1]
    virtualbox-iso:
    virtualbox-iso: Pinging 127.0.0.1 with 32 bytes of data:
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso: Reply from 127.0.0.1: bytes=32 time<1ms TTL=128
    virtualbox-iso:
    virtualbox-iso: Ping statistics for 127.0.0.1:
    virtualbox-iso: Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    virtualbox-iso: Approximate round trip times in milli-seconds:
    virtualbox-iso: Minimum = 0ms, Maximum = 0ms, Average = 0ms
    virtualbox-iso: ==> Script exiting with errorlevel 0```

**Comment by dragetd** [comment]
We keep defining the download URLs at several spots. It makes them hard to manage and update. I am preparing a PR (should be up in a few minutes) which also updates a lot of URLs (and thus will cause even more merge-issues with this one).

I'd highly welcome an attempt to move all URLs of additional tools to one spot. :-/

**Comment by daxgames** [comment]
I also have an updated version of this that uses this new ps1_download function assuming #179 gets merged.

**Pull request closed without merging**
