### PR TITLE
Hyper-V tried sneaking into post-processors

### PR DESCRIPTION
**Pull request by dragon788**
This caused a failure to build from this template.

### CODE REVIEW

**Comment by arizvisa** [comment]
@dragon788, do you mind re-basing this?

**Comment by dragon788** [comment]
I’ll take a look this week and see what exactly changed to cause the conflict and try to get it fixed.

**Comment by arizvisa** [comment]
Thx. eval-win7x64-enterprise-cygwin.json has the exact same problem, so once you re-base this. I'll fix that one too.

**Comment by arizvisa** [comment]
Do you mind if I close this PR and fix both eval-win81x64-enterprise.json, and eval-win7x64-enterprise-cygwin.json?

**Comment by dragon788** [comment]
That would be great, sorry I haven't had a chance to get back to this, it's been a crazy December.

Also, it's great to see somebody dusting off some of the Boxcutter repos, hopefully some of the others get a bit more activity as well.

**Comment by arizvisa** [comment]
Thx. Fixed it with PR #193.

**Pull request closed without merging**
