### PR TITLE
Generating correct chef-client download URL based on x.y.z version

### LINKED ISSUE #32: Chef installation doesn't work if an x.y.z version is specified
Chef 11.18.10+ installation doesn't work if version is specified. Apparently Chef has changed URLs for MSIs to this format:
https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-11.18.10-1.msi
That happened during the release of 11.18.10

This can't be fixed by passing a custom URL variable via Makefile.local either, because only "CM" and "CM_VERSION" get passed through to the VM.

Overall, for all versions: CM_VERSION syntax does not match the one described in readme:
- The value of CM_VERSION should have the form x.y or x.y.z, such as CM_VERSION := 11.12.4

In fact the only value that would work right now would be "11.12.4-1". We can safely add "-1" to simplify interface, for all the released versions of Chef-client with the following exceptions:
- https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-windows-11.12.8-2.windows.msi
- https://opscode-omnibus-packages.s3.amazonaws.com/windows/2008r2/x86_64/chef-client-11.4.4-2.windows.msi

### PR DESCRIPTION
**Pull request by 4min**
This fixes #32
Not very future-proof for future chef-client 11 builds, but as we don't know where they'll be headed - this would work for now.

### CODE REVIEW

**Comment by annawake** [comment]
That I actually have some information about ;-)  You actually need to use the Omnitruck API to get the chef-client URL: https://docs.chef.io/api_omnitruck.html

**Comment by annawake** [comment]
So rather than hardcoding the versions like this, omnitruck should be the way.

**Comment by 4min** [comment]
Thanks, great idea. Please decline this PR, a new one is on the way.

**Comment by annawake** [comment]
Closed

**Pull request closed without merging**
